jbolda/covector

.changes/abstract-cwd.md
.github/workflows/test.yml
__fixtures__/integration.js-and-rust-with-changes/.changes/config.json
__fixtures__/integration.js-and-rust-with-changes/.changes/first-change.md
__fixtures__/integration.js-and-rust-with-changes/.changes/second-change.md
__fixtures__/integration.js-and-rust-with-changes/cli/tauri-bundler/Cargo.toml
__fixtures__/integration.js-and-rust-with-changes/cli/tauri.js/package.json
__fixtures__/integration.js-and-rust-with-changes/tauri-api/Cargo.toml
__fixtures__/integration.js-and-rust-with-changes/tauri-utils/Cargo.toml
__fixtures__/integration.js-and-rust-with-changes/tauri/Cargo.toml
package.json
packages/apply/index.test.js
packages/assemble/index.test.js
packages/covector/__snapshots__/index.test.js.snap
packages/covector/index.test.js
packages/covector/package.json
packages/covector/src/run.js

The later commands, `version` and `publish` are rather side effect heavy which is making this harder to test. It may be worth addressing this and spring things up as we button up the code. This is some minor implementations and will likely come back around with later PRs to address the other cli commands.

chore: full integration test

---

.changes/abstract-cwd.md
.changes/fix-toml-string.md
.changes/rust-bumps-properly.md
__fixtures__/pkg.rust-multi/pkg-a/Cargo.toml
__fixtures__/pkg.rust-multi/pkg-b/Cargo.toml
packages/action/dist/index.js
packages/apply/__snapshots__/index.test.js.snap
packages/apply/index.js
packages/apply/index.test.js
packages/files/index.js

This adds test for bump rust packages. It also includes a couple fixes of bugs discovered while writing the tests.

chore: test rust pkg

---

.changes/config.json
packages/action/dist/index.js

This isn't yet implemented, but it needs to be soon for my sanity.

chore: update config to build action on version lifecycle

---

.changes/prefer-inline-objects-in-rust.md
.changes/rust-dep-bumps.md
__fixtures__/pkg.rust-multi-no-patch-dep/Cargo.toml
__fixtures__/pkg.rust-multi-no-patch-dep/pkg-a/Cargo.toml
__fixtures__/pkg.rust-multi-no-patch-dep/pkg-b/Cargo.toml
__fixtures__/pkg.rust-multi-object-dep/Cargo.toml
__fixtures__/pkg.rust-multi-object-dep/pkg-a/Cargo.toml
__fixtures__/pkg.rust-multi-object-dep/pkg-b/Cargo.toml
__fixtures__/pkg.rust-multi-object-no-patch-dep/Cargo.toml
__fixtures__/pkg.rust-multi-object-no-patch-dep/pkg-a/Cargo.toml
__fixtures__/pkg.rust-multi-object-no-patch-dep/pkg-b/Cargo.toml
packages/action/dist/index.js
packages/apply/__snapshots__/index.test.js.snap
packages/apply/index.js
packages/apply/index.test.js
packages/covector/__snapshots__/index.test.js.snap
packages/files/index.js
packages/files/package.json

feat: handle object bumps

---

.changes/add-dry-run.md
.changes/config.json
.changes/pipe-pkgfile.md
.github/workflows/run-version-or-publish.yml
packages/action/dist/index.js
packages/apply/index.js
packages/assemble/index.js
packages/changelog/index.js
packages/covector/__snapshots__/index.test.js.snap
packages/covector/index.test.js
packages/covector/src/cli.js
packages/covector/src/run.js

This let's one better test config and get a view into what a command will exectute.

feat: --dry-run mode

---

.changes/yield-getPublishedVersion.md
__fixtures__/integration.js-and-rust-with-changes/.changes/config.json
packages/covector/__snapshots__/index.test.js.snap
packages/covector/src/run.js

otherwise it was returning a generator and would never skip publishing

fix: yield getPublishedVersion check

---

README.md

Working to address and close #118.
Is anything left unclear still?

chore: add better usage and GitHub action descriptions

---

.changes/stream-commands.md
packages/action/package.json
packages/command/index.js
packages/command/package.json
packages/covector/__snapshots__/index.test.js.snap
packages/covector/index.test.js
packages/covector/package.json

Stream command output instead of waiting for completion. This is particularly helpful when a command hangs unexpectedly (such as when it asks for input in CI).

stream command output through new @effection/node version

---

.github/workflows/run-version-or-publish.yml

This upgrade fixes is the issue with the deprecated set envs.

chore: upgrade create-PR action

---

README.md

This can be used for any general publishing, and use of "polyglot" implied bindings in multiple languages. The use of the word "sane" also is not helpful, and possibly implies unwanted thoughts.
Appreciate the thoughts from @maxcell on this. 🙏

improve motto to better explain the value

---

.changes/init-init-command.md
.changes/missing-workspace-refs.md
README.md
packages/apply/package.json
packages/assemble/package.json
packages/covector/package.json
packages/covector/src/cli.js
packages/covector/src/init.js

Run the `init` command to bootstrap the configuration for covector.

feat: init command

---

.changes/fix-noop-bumps.md
packages/apply/index.js
packages/assemble/__snapshots__/index.test.js.snap
packages/assemble/index.js
packages/assemble/index.test.js

Bumps were creeping in that were not valid. Fix to no-op on these.

fix: additional bump type is no-op

---

.changes/init-github-folder.md
packages/covector/src/init.ts

The `init` should consider if there is an existing `.github` folder. Also, set the default action version to `major.minor`.

fix: init github folder

---

.changes/config.json
.changes/pipe-pkgCommandsRan.md
.changes/pull-changelog-entry.md
.changes/split-merge-command.md
packages/action/utils.ts
packages/apply/package.json
packages/assemble/__snapshots__/index.test.ts.snap
packages/assemble/index.test.ts
packages/assemble/index.ts
packages/changelog/index.test.ts
packages/changelog/index.ts
packages/command/index.test.ts
packages/command/index.ts
packages/command/package.json
packages/covector/__snapshots__/index.test.ts.snap
packages/covector/index.test.ts
packages/covector/src/run.ts
packages/files/index.ts
tsconfig.json

This PR should fix the pipe into the Github Releases, and also adds the changelog as part of that pipe.

fix: GitHub release pipe

---

.changes/init-setup-node-v2.md
.github/workflows/run-status.yml
.github/workflows/run-version-or-publish.yml
package-lock.json
package.json
packages/covector/src/init.ts

Fix CI volta/action clash and remove postinstall (might be an issue too? but don't need it anyways).

fix: remove postinstall and adjust node setup for CI

---

.changes/deps-update-2022-04.md
package-lock.json
package.json
packages/action/package.json
packages/action/src/utils.ts
packages/action/test/mock-check.test.ts
packages/apply/package.json
packages/assemble/package.json
packages/changelog/package.json
packages/command/package.json
packages/covector/package.json
packages/files/package.json
packages/types/package.json

There are a handful of major dependencies that are worth upgrading for the latest features and security fixes.
Upgrade and test.

dep update

---

.changes/upgrade-to-effection-v2.md
package-lock.json
packages/action/package.json
packages/apply/package.json
packages/assemble/package.json
packages/changelog/package.json
packages/command/package.json
packages/covector/package.json

Did some work upstream to handle ctrlc-windows with a lower maintenance burden. Upgrade to pull this work in.

bump effection to latest on v2

---

package-lock.json
packages/action/package.json
packages/apply/package.json
packages/assemble/package.json
packages/changelog/package.json
packages/command/package.json
packages/covector/package.json
packages/files/package.json
packages/types/package.json

Upgrading TS to 4.8. As this is primarily devDeps, not including a package bump.

typescript 4.8

---

.changes/max-cjs-inquirer-globby.md
package-lock.json
package.json
packages/covector/package.json
packages/covector/test/__snapshots__/command-init.test.ts.snap
packages/files/package.json

Bumping inquirer and globby to the highest version before we need to switch to ESM.

bump inquirer and globby to highest CJS version

---

.changes/changelog-multi-line-format.md
.changes/changelog-tags.md
.changes/config.json
.changes/rust-workspace-inheritance.md
.changes/ts-4.9.md

chore: add tags for existing change files

---

.changes/changelog-multi-line-format.md
.changes/changelog-tags.md

These features definitely need a minor on the main package.

minor for new features

---

packages/covector/README.md

chore: typo

---

.changes/build-deps-and-target.md
.changes/changelog-deps-version-number.md
.changes/command-retries.md
.changes/config.json
.changes/dep-range-bump-without-release.md
.changes/fix-bump-deps.md
.changes/pull-changelog-depth-two.md
.changes/use-functions-for-typical-operations.md

Apply change tags to everything so it is categorized.

categorize existing changes with new change tags

---

.changes/change-pr-299.md
.changes/github-comment-status.md
.changes/silent-apply-and-status.md
.github/workflows/run-on-pr.yml
package-lock.json
packages/action/README.md
packages/action/action.yml
packages/action/package.json
packages/action/src/comment/formatGithubComment.ts
packages/action/src/comment/postGithubComment.ts
packages/action/src/comment/types.ts
packages/action/src/index.ts
packages/action/src/utils.ts
packages/apply/src/apply.ts
packages/assemble/src/index.ts
packages/assemble/test/assemble.test.ts
packages/assemble/test/merge-config.test.ts
packages/covector/src/run.ts
packages/covector/src/status.ts
packages/covector/test/__snapshots__/dry-run.test.ts.snap
packages/covector/test/__snapshots__/main.test.ts.snap
packages/covector/test/main.test.ts
packages/files/package.json
packages/files/src/index.ts
packages/types/package.json
packages/types/src/index.ts

It is helpful to lift some context from current changes into the PR. This looks to add an updatable PR comment to handle this lift.
Github comment which is updatable due to a comment tag.

Status Context Comment On PR

---

.github/workflows/run-on-pr.yml
.github/workflows/run-version-or-publish.yml

We wrote the feature, but didn't turn it on 😁 .

turn on recognizeContributors

---

packages/action/src/index.ts
packages/action/src/pr/getCommitContext.ts

Updated the query in #312, but missed updating the logic to expect it as optional.

reviewers may not be in query

---

packages/changelog/src/index.ts

Forgot to remove the contributor from the end in #312.
*hand over face*

remove contributor from end of change

---

.changes/checkout-v4-create-pr-v6.md
.github/workflows/run-on-pr.yml
.github/workflows/run-version-or-publish.yml
.github/workflows/test.yml
__fixtures__/integration.js-with-publish-error/.changes/config.json
__fixtures__/integration.js-with-retrying-publish-error/.changes/config.json
packages/covector/src/init.ts
packages/covector/test/helpers.ts
packages/covector/test/integration/main.test.ts

Update `init` command with the latest action versions: `checkout@v4` and `create-pr@v6`.
Search and replace.

init actions to checkout@v4, create-pr@v6

---

.github/workflows/comment-on-forks.yml

For downstream use, it is nice to log out these values for the visibility and debugging here.
Log then `if` the actual step.

log out workflow run logic for checking

---

.github/workflows/comment-on-forks.yml

Forgot to remove the root logic for the `if:` block in #325.

actually remove root workflow_run if

---

.github/workflows/comment-on-forks.yml

Our check wasn't working and their API docs are not complete enough. Dump the full context to check.

dump full github context on workflow_run

---

.github/workflows/comment-on-forks.yml

The `workflow_run` needed the token...

add token to workflow_run status

---

.changes/no-changes-have-link.md
packages/action/src/comment/formatGithubComment.ts
packages/types/src/index.ts

When there are no changes, we want to also include a link to add a change file. Arguably the more important situation too!
Add content below some as in the comment with existing changes.

Include link when there are no changes

---

.github/workflows/run-version-or-publish.yml

Missing permission to create the Version Packages PR.

pull-requests permission required for Version Packages PR

---

.changes/init-new-features-and-permissions.md
packages/covector/src/init.ts

`init` can toggle on the new changelog contributor mention and comments in PRs.

`init` changelog contributor tag and PR comment

---

.changes/cwd-cli-option.md
packages/covector/src/cli.ts

The CLI accepts a `--cwd` option.

--cwd CLI option

---

.github/workflows/comment-on-forks.yml

Action was running on forks but pointing to an outdated tag.

fix comment-on-forks action tag
