jbolda/covector

- .github/workflows/run-version-or-publish.yml
This is needed to handle the signing into npm for publishing.
> fix: setup node in publish workflow

- .github/workflows/run-version-or-publish.yml
The registry url is needed in setup-node to login to npm.
> fix: publish login needs registry url

- .changes/config.json
- .changes/getPublishedVersion-shift.md
- packages/command/index.js
- packages/covector/__snapshots__/index.test.js.snap
- packages/covector/package.json
- packages/covector/src/run.js
Previously we were checking prior to each command in the publish sequence. This worked find for prepublish and publish (albeit a bit redundant), but would never run postpublish as it had literally just published and would skip everything. Shift it out to one run up front.
> fix: getPublishedVersion check shift

- .changes/multiple-publish.md
- __fixtures__/integration.js-with-subcommands/.changes/config.json
- __fixtures__/integration.js-with-subcommands/package.json
- __fixtures__/integration.js-with-subcommands/packages/package-one/package.json
- __fixtures__/integration.js-with-subcommands/packages/package-two/package.json
- packages/assemble/index.js
- packages/command/index.js
- packages/covector/__snapshots__/index.test.js.snap
- packages/covector/index.test.js
- packages/covector/src/run.js
Any command prepended with publish will now invoke the related version check command prepended with getPublishedVersion.
> feat: allow multiple publishes

- .github/workflows/run-version-or-publish.yml
It was always "failing" the check which effectively ignores the `if`. Fix for proper check.
> fix: workflow version mode check

- lerna.json
We don't need to use it anymore as covector can handle this function now.
> chore: remove lerna config file

- .changes/filter-packages.md
- __fixtures__/assemble/packages/assemble1/package.json
- __fixtures__/assemble/packages/assemble2/package.json
- __fixtures__/assemble/packages/namespaced-assemble1/package.json
- __fixtures__/assemble/packages/namespaced-assemble2/package.json
- packages/action/action.yml
- packages/action/index.js
- packages/action/index.test.js
- packages/action/utils.js
- packages/assemble/__snapshots__/index.test.js.snap
- packages/assemble/index.js
- packages/assemble/index.test.js
- packages/assemble/package.json
- packages/covector/src/run.js
Some workflows require different actions for different packages. Most of this can be codified into config. However there are cases where you may need to run a command for a dynamic set of packages.
> feat: filter pkgs

- .changes/extra-package-output.md
- packages/action/action.yml
- packages/action/index.js
Add extra outputs for which packages published and a list of packages. This is useful for chaining runs of the action together.
> feat: add action output to better show which packages published

- .changes/allow-running-functions.md
- .changes/config.json
- .changes/reorder-github-release-creation.md
- packages/action/action.yml
- packages/action/index.js
- packages/action/utils.js
- packages/assemble/index.js
- packages/command/index.js
- packages/command/index.test.js
- packages/covector/__snapshots__/index.test.js.snap
- packages/covector/index.test.js
- packages/covector/src/run.js
When multiple packages are published, it is possible that one or more succeeds followed by a failure to publish. When a failure occurred in this instance, the packages that were published would not have a Github Release created as they were created after all `prepublish`/`publish`/`postpublish` steps were run. This PR adjusts the functionality to create the release after the `publish` step completes for each package.
We added an API to allow modifying the config by passing a function. This let's us inject functions that can be run.
It will be difficult for the user to pass a function without any errors (and it might likely require tests). I don't presume that this will be used outside of the action though.
> feat: reorder GitHub release step

- .changes/validate-apply-during-status.md
- __fixtures__/pkg.rust-multi-object-path-dep-only/Cargo.toml
- __fixtures__/pkg.rust-multi-object-path-dep-only/pkg-a/Cargo.toml
- __fixtures__/pkg.rust-multi-object-path-dep-only/pkg-b/Cargo.toml
- packages/apply/__snapshots__/index.test.js.snap
- packages/apply/index.js
- packages/apply/index.test.js
- packages/covector/__snapshots__/index.test.js.snap
- packages/covector/src/run.js
- packages/files/index.js
This adds a guardrail within the `status` command to surface errors during the PR process rather than later on.
Closes #134.
> feat: version bump guardrail

- .changes/allow-special-bump-types.md
- .changes/config.json
- packages/assemble/__snapshots__/index.test.js.snap
- packages/assemble/index.js
- packages/assemble/index.test.js
Adds a hard error for an bump type that is not valid, and adds a config option to add more options.
One might add more options that encompass actions in the repo (such as `housekeeping`) that require a PR, but don't necessarily change the code and require incrementing the version number. This would enable _always_ requiring a change file on a PR which improves the ability to enforce it.
closes #131, closes #132
> feat: extra bump types

- README.md
- packages/apply/README.md
- packages/assemble/README.md
- packages/changelog/README.md
- packages/command/README.md
- packages/covector/README.md
- packages/files/README.md
This PR shifts around the readme. The root readme is now more of a general "about this monorepo" with the `covector` package folder readme containing the usage. This will mean that the usage docs get pushed to npm.
> feat: shift docs for npm publishing

- .changes/rust-init.md
- packages/covector/src/init.js
Fix `init` Rust based packages coming in as undefined. The `.toml` has the name nested under `.packages`.
> fix: rust based packages undefined

- .changes/bump-effection-v1.md
- .changes/temp-execa-shell.md
- packages/action/package.json
- packages/command/index.test.ts
- packages/command/index.ts
- packages/command/package.json
- packages/covector/package.json
Piped commands need to shell out. We receive a string, so we can just search for the pipe operator. Temp use `execa` to handle this.
> fix: piped commands

- .changes/add-missing-hoisted-deps.md
- jest.config.js
- package.json
- packages/apply/package.json
- packages/apply/rollup.config.js
- packages/apply/tsconfig.json
- packages/assemble/package.json
- packages/assemble/rollup.config.js
- packages/assemble/tsconfig.json
- packages/changelog/package.json
- packages/changelog/rollup.config.js
- packages/changelog/tsconfig.json
- packages/command/package.json
- packages/command/rollup.config.js
- packages/command/tsconfig.json
- packages/covector/package.json
- packages/covector/rollup.config.js
- packages/covector/tsconfig.json
- packages/files/package.json
- packages/files/rollup.config.js
- packages/files/tsconfig.json
- tsconfig.json
Fixing latent rollup and tsconfig issues as discovered with @dagda1. Bump the remaining devDeps. Fix a few missing deps that were only working due to hoisting.
> chore: bump devDeps and fix tsconfig/rollup issues

- .changes/init-simplify-and-nicknames.md
- packages/covector/src/init.ts
This PR adjust the `init` command to remove the complex commands as I realized chatting with @minkimcello in #167. It also adjusts the publish check to use the package.json name which makes it easier to switch to using nicknames (which I suspect will be one of the first customizations someone might consider). This came up in https://github.com/thefrontside/simulacrum/pull/30.
> fix: improve init output for easier onboarding

- .github/workflows/run-preview.yml
The covector action is being called from a branch that no longer exists and therefore the preview workflow is failing. These changes have already been addressed in #187 but it's broken for all the other PRs.
- Replaced yarn scripts with npm
- Added volta action
- Call action locally and not remotely
> fix: update preview workflow

- packages/apply/package.json
- packages/apply/tsconfig.json
- packages/assemble/package.json
- packages/assemble/tsconfig.json
- packages/changelog/package.json
- packages/changelog/tsconfig.json
- packages/command/package.json
- packages/command/tsconfig.json
- packages/covector/package.json
- packages/covector/tsconfig.json
- packages/files/package.json
- packages/files/tsconfig.json
- tsconfig.base.json
There were a few things that needed to change to stop `tsc` getting confused
Change
```json
"main": "dist/index.js",
"files": [
"dist/**/*"
],
```
to
```json
"main": "dist/index.js",
"types": "dist/index.d.ts",
```
The `tsconfig.base.json` was updated to set things like `"declaration": true`
I would put all application code in `./src` in each package.
> fix package.json fields and base tsconfig.json

- .changes/config.json
- .changes/npm-and-ts-project-ref.md
- .changes/preview-action-bump.md
- __fixtures__/integration.js-and-rust-with-changes/tauri/Cargo.toml
- packages/apply/index.ts
I noticed a bug in covector on how it's supposed to bump inter-dependent packages. It wasn't showing up in tests but in the covector setup _within_ the covector monorepo workspace so this PR is meant to locate why that was happening.
- Before I get into how I fixed the bug, I found another bug from one of my refactors in #187. I had forgotten to rename one of the argument variables and that's been addressed.
- I also accidentally deleted a fixture file so that was reintroduced in this PR
- The bug bug came from the covector config file. The packages listed in the config file must match the package names listed in the packages' package.json files. Fixing this allowed covector to properly bump all the packages and dependencies. See data below in comments.
> bug: Fix bumping error

- .changes/throw-on-empty-change-file.md
- packages/assemble/index.test.ts
- packages/assemble/index.ts
Throw an error if the change file is malformed or otherwise missing a package bump. This deals with #201.
> fix: throw error on empty change file

- .changes/pipe-tag-template.md
- __fixtures__/integration.js-and-rust-for-preview/.changes/config.json
- packages/action/__snapshots__/index.test.ts.snap
- packages/action/src/index.ts
- packages/apply/index.test.ts
- packages/assemble/index.ts
- packages/command/index.ts
- packages/covector/__snapshots__/index.test.ts.snap
- packages/covector/index.test.ts
- packages/covector/src/run.ts
To add tags to the preview packages. It's fine as is at the moment because the pre-release semver syntax _without_ bumping means the latest tag will not be compromised but it's still nice to tag the preview packages for NPM.
- `action.command.preview` will now pass in `covector({ ..., branchTag })`
- the branchTag takes the branch name from the context of the workflow
- the branch is then converted in the same manner our current preview action treats its tags:
```js
const branchTag = branchName.replace(/(?!.\_)\_/g, '__').replace(/\//g, '_');
```
- ~the `branchTag` argument gets utilized _within_ `covector`'s preview command by mutating the publish commands~
- ~alternatively I could've passed in the branchTag into `mergeIntoConfig` but there's a lot going on in there and mutating the …
> feat: Add dist-tag for preview publishing... and fix the published boolean bug

- .changes/abstract-ext-log.md
- packages/apply/index.ts
- packages/files/index.ts
This shifts all considerations and logic that are dependent on the shape of the package file (and consequently the file extension) into the `files` package. When getting and setting the version number in `assemble`, be it the main version or a dep/devDep, we can now just use the function which abstracts over all of these considerations.
Pulled all functionality out into a separate function, and then copied it into the `files` packages. Confirmed that the tests passed and no snapshots changed.
> feat: normalize version number pulling and setting

- .changes/action-pipe-as-output.md
- packages/action/__snapshots__/index.test.ts.snap
- packages/action/action.yml
- packages/action/index.test.ts
- packages/action/src/index.ts
- packages/assemble/__snapshots__/index.test.ts.snap
- packages/assemble/index.test.ts
- packages/assemble/index.ts
- packages/covector/index.test.ts
- packages/covector/src/run.ts
This adds some additional tests around the Github action output. We also adjusted the output from `assemble` and `covector` to expose the information being piped into the commands. This is then exposed as an output from the Github action. Potentially useful when composing actions.
> feat: github action output template pipe

- .changes/fix-covector-dist.md
- packages/covector/package.json
Installing covector@0.6.0 from nom and runnning any commands crashes because files `./run` and `./cli` are missing. This PR fixes that.
> Include all file in dist directory

- .changes/trim-prerelease-for-preview.md
- __fixtures__/pkg.js-single-prerelease-json/package.json
- __fixtures__/pkg.js-yarn-prerelease-workspace/package.json
- __fixtures__/pkg.js-yarn-prerelease-workspace/packages/pkg-a/package.json
- __fixtures__/pkg.js-yarn-prerelease-workspace/packages/pkg-b/package.json
- packages/apply/src/index.ts
- packages/apply/test/__snapshots__/index.test.ts.snap
- packages/apply/test/index.test.ts
- packages/covector/test/__snapshots__/index.test.ts.snap
[This](https://github.com/thefrontside/material-ui-interactors/pull/36#issuecomment-866980082) discussion. The preview version will stack on top of a prerelease version so `1.0.0-beta.1` will turn into `1.0.0-beta.1-my-preview.12345`.
```
publish preview ?
in prerelease ?
apply patch to revert prerelease (without actually bumping patch) and then apply preview version
not prerelease ?
just apply preview version
```
> Preveiw versioning for packages in prerelease mode

- packages/action/__snapshots__/index.test.ts.snap
- packages/action/src/index.ts
"bumping applicable packages" is unnecessarily vague. 
Instead,  we we can be very precise: "release the following versions of these packages"
> clarify consequences of merging PR

- .changes/include-license-files.md
- packages/action/LICENSE
- packages/apply/LICENSE
- packages/assemble/LICENSE
- packages/changelog/LICENSE
- packages/command/LICENSE
- packages/covector/LICENSE
- packages/files/LICENSE
- packages/types/LICENSE
Good morning (for me anyway)!
I noticed the packages where missing license files when downloaded from nom, as this causes some issues with automated checking tools I though I shoot a PR to fix that 😉
> chore: add license files to packages

- .changes/deprecation-github-output.md
- package-lock.json
- packages/action/package.json
Updates [`@actions/core`](https://github.com/actions/toolkit/tree/main/packages/core) to 1.10.0 and [`@actions/github`](https://github.com/actions/toolkit/tree/main/packages/github) to 5.1.1. The `@actions/core` update resolves [deprecation warnings](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) coming from calls to `core.setOutput()`, which will be removed in June 2023.
Updates dependencies
N/A
> chore(action): Update actions/core and actions/github dependencies

- .changes/range-on-deps.md
- packages/apply/src/index.ts
This is particularly useful for Cargo dependencies where you might want to pin the dependency to the minor release, e.g. in Cargo.toml the version is set to `=1.2` and covector must bump it to `=1.3`.
Regex match for common version requirement characters `~`, `^` and `=` and add them as the new version prefix.
> feat: keep dependency version requirement

- .changes/dep-bump-from-main.md
- packages/apply/src/index.ts
- packages/apply/test/__snapshots__/apply.test.ts.snap
- packages/apply/test/apply.test.ts
- packages/assemble/src/index.ts
The dep bumps presume that we could simply blindly increment the version that was previously set. This works _most_ of the time with automatic bumps, but if any user adds a dep or a bump is missed then it causes issues. The bump could be incremented but still be behind.
This seeks to use to version _just_ set as the version for the dep bumps as well.
> dep bumps use main version directly vs presuming increment is correct

- .changes/changelog-commits-ternary.md
- packages/changelog/src/index.ts
We were occasionally getting an `undefined` on the bullet points representing commits in the changelog. Addressing the logic to make it more clear.
> remove ternary and explicitly consider changelog commit bullet points

- .github/workflows/test.yml
- packages/assemble/src/index.ts
- packages/assemble/test/git.test.ts
The `git log` function in assemble appeared to be returning odd results. Threw a test on it to confirm it isn't an issue.
> add git log assemble test

- .github/workflows/run-on-pr.yml
- packages/assemble/test/git.test.ts
In merging in the Version Packages PR, we deleted a file which one of the git log tests relied upon. Fix this test.
We can add a `--` for inform git that it is specifically a file reference and not throw an error. This should enable to it to work even after the file is deleted.
> fix failing git test due to missing change file

- .changes/config.json
In updating `npm`, it started throwing errors when running commands in the package folder. This broke the publish check as it expects to only have the version number returned.
> silent errors on npm view as it breaks the check

- .changes/changelog-multi-line-format.md
- .changes/format.md
- packages/action/test/__snapshots__/e2e.test.ts.snap
- packages/apply/src/parents.ts
- packages/apply/test/__snapshots__/changes-considering.test.ts.snap
- packages/changelog/src/index.ts
- packages/changelog/test/fill-changelog.test.ts
- packages/changelog/test/read-changelog.test.ts
- packages/command/test/sh.test.ts
- packages/covector/test/__snapshots__/dry-run.test.ts.snap
- packages/covector/test/__snapshots__/main.test.ts.snap
- packages/covector/test/__snapshots__/preMode.test.ts.snap
- packages/covector/test/main.test.ts
- packages/covector/test/preMode.test.ts
- packages/types/src/index.ts
Current changelogs are cluttered with commits noise, and restricted to single-line changelogs
1. Indent multi-line changelogs so it renders correctly under its bullet point (done)
2. Reduce the commit noise to only the short commit hash and the PR it was introduce in (done)
3. Group changelogs of dependencies under one bullet-point for each dependency (having a bit trouble with, explained below)
Ultimately a changelog could look like the following:
- Fix a bug in this package
- Add a feature to this package but needs to be explained in
multiple paragraphs
This could also include 
```
code blocks
```
and also lists:
- a1
```
run this cmd
```
- a2
- a3
- Fix another bug in this package
- <details>
<summary>Bumped due to a bump in `package-utils` </summary>
- A fix in package-utils
- A …
> feat(changelog): enhance format for multi-line and reduce commit noise

- .changes/fix-bump-deps.md
- packages/apply/src/apply.ts
The current bumpDeps function expects the configuration object to use the actual package name as key, which might not be desired if the package name is large or has namespaces. This PR changes the mechanism to try to pull the package version from the file.
Try to pull the package version from the file object.
Add a name field on the package definition or keep expecting the package name to match.
Currently only supports Rust and JavaScript packages.
> fix(apply): try to use actual package name when bumping deps

- .changes/pull-changelog-depth-two.md
- packages/changelog/src/index.ts
- packages/changelog/test/read-changelog.test.ts
The Github releases were pulling in the full changelog instead of strictly the last change. Fixing this.
The approach to grab the appropriate text did not consider headings deeper than two. Prior to adding changeTags, we only had a level one and level two heading so this issue did not present itself until _after_ publishes had gone out that contained level three headings (from the changeTags).
> changelog pull should consider headings deeper than two

- .changes/changelog-deps-version-number.md
- .changes/dep-range-bump-without-release.md
- .gitattributes
- __fixtures__/pkg.js-yarn-workspace/packages/pkg-c/package.json
- __fixtures__/pkg.js-yarn-workspace/packages/pkg-one/package.json
- packages/action/src/index.ts
- packages/action/test/__snapshots__/e2e.test.ts.snap
- packages/apply/package.json
- packages/apply/src/apply.ts
- packages/apply/src/parents.ts
- packages/apply/test/__snapshots__/apply-preview.test.ts.snap
- packages/apply/test/__snapshots__/apply.test.ts.snap
- packages/apply/test/__snapshots__/changes-considering.test.ts.snap
- packages/apply/test/apply-preview.test.ts
- packages/apply/test/apply.test.ts
- packages/apply/test/changes-considering.test.ts
- packages/changelog/src/index.ts
- packages/covector/test/__snapshots__/dry-run.test.ts.snap
- packages/covector/test/__snapshots__/main.test.ts.snap
- packages/covector/test/__snapshots__/preMode.test.ts.snap
- packages/covector/test/main.test.ts
- packages/covector/test/preMode.test.ts
Deps with a range such as `^` that did not have a release would throw an `undefined` error.
Also, additional context on the `Dependencies` section in the changelog would be most helpful.
Removed and then further adjusted how these roll up bumps are handled. This now relies on the changelog `Dependencies` section logic to note all changes rather than the previous, naive "Bumped due to dependency."
> skip bump on range and add version number for deps in changelog

- .changes/config.json
- .changes/use-functions-for-typical-operations.md
- packages/command/src/index.ts
- packages/command/test/attemptCommand.test.ts
- packages/command/test/commandFailure.test.ts
- packages/command/test/confirmCommandsToRun.test.ts
- packages/command/test/fetchCommand.test.ts
- packages/covector/README.md
- packages/types/src/index.ts
In using `covector`, we have found there are a handful of very typical operations that make sense to abstract into "built-in" operations. Specifying the `use` in a command with `options` to access these functions.
Added a new API that calls specific abstracted chunks of logic with passed options instead of using shell commands.
> `use` commands for typical operations

- .changes/change-log-fallback-deps-tag.md
- packages/changelog/src/index.ts
The built-in `deps` tag fallback was always rendered before the tags defined in the config when it should've been rendered last.
> fix: render `deps` tag fallback after config tags

- .changes/assemble-getpublishedversion-object.md
- packages/assemble/src/index.ts
- packages/command/src/index.ts
- packages/command/test/fetchCommand.test.ts
The command handled a `getPublishedVersion` as object, but assemble didn't. Fixing that.
Check for an object in the assemble process.
> assemble handles getPublishedVersion as object

- .changes/config.json
The section for the Github Release incorrectly says "Cargo" and looked a bit wonky. Cleaning it up.
> fix github publish details section

- .changes/timeout-in-config-schema.md
- packages/files/src/schema.ts
The `timeout` property was missing in the config schema and incorrectly throwing an error.
Add it to the schema.
> `timeout` in `config.json` schema

- .github/dependabot.yml
We don't need to update deps in the fixtures directory as we are not installing these nor shipping them.
Try honing in dependabot to ignore fixture dirs.
> Dependabot Ignores Fixture Directory

- .changes/fetch-command-user-agent.md
- packages/command/src/index.ts
- packages/command/test/fetchCommand.test.ts
The `crates.io` endpoint now requires a user agent. Including an agent with all fetch requests to avoid the 403 from crates.io.
> include fetch command user agent

- .changes/config.json
In #303, we missed updating the config to point `files` properly at depending on the new `toml` pkg. This threw a failure in our lockfile sync step (since that version wasn't bumped there and it isn't published yet).
> files pkg depends on toml pkg

- .changes/remove-github-md-links.md
- packages/action/src/index.ts
The changelog and subsequent comment include markdown links to GitHub. The links are inserted in the changelog file as it may be viewed in many contexts including outside of GitHub. If we insert the content in GitHub however, it will resolve its own links to provide additional context. We should remove these links to allow the GitHub platform to handle this (including interlinking to the Version Packages PR).
As this is GitHub-specific, we handle this directly in the action and remove the links through regex. With the specificity employed, it is unlikely to be accidentally destructive.
> remove github links in version comment

- .changes/recognize-contributors.md
- packages/action/src/pr/getCommitContext.ts
- packages/changelog/src/index.ts
- packages/changelog/test/fill-changelog.test.ts
- packages/changelog/test/read-changelog.test.ts
In #307, we added the opt-in feature to recognize contributors and reviewers. After discussions with @amrbashir, we removed reviewers over concerns of spam and possible verbosity issues. Additionally, the placement of the contributor recognition was awkward.
By removing the reviewers, this made it easier to justify putting the PR author directly after the number.
> remove reviewer recognition and shift contributor note

- packages/action/src/index.ts
The changelog regex didn't consider naked github.com urls, and it should.
Updated the regex to consider `www.` as optional.
> update changelog regex for naked github url

- .changes/exports-dependent-conditions-import-tsx.md
- package-lock.json
- package.json
- packages/apply/package.json
- packages/assemble/package.json
- packages/changelog/package.json
- packages/command/package.json
- packages/covector/package.json
- packages/files/package.json
- packages/toml/package.json
- packages/types/package.json
With the upgrade to v20 of node, we can use both conditions and the import to run _every_ package directly with the typescript files. This avoids the requirement of builds and the errors attributed to stale builds when checking code locally (outside of tests).
Set the `exports` in each package to import the `ts` dependent on the `--condition`. With this, we can use `--import=tsx` to run every package through it's Typescript file.
> node `--conditions` with exports and `--import=tsx`

- .github/workflows/comment-on-forks.yml
`head_repository` is the ticket for determining if the `workflow_run` is executing off a PR from a fork. This is based on context in #327.
> use head_repository on workflow_run to determine fork

- .github/workflows/comment-on-forks.yml
The `main` branch doesn't yet have the built `dist` to test the action. Switch to `release`.
> workflow_run use @release branch

- package-lock.json
- packages/action/package.json
- packages/action/src/comment/postGithubCommentFromArtifact.ts
Previously through a muddle of examples, we expecting separate files but instead we had a single zip file which caused it to fail.
Handle downloading the zip file including the unzip, then handle each file separately.
> artifact download should handle single zip file

- .github/workflows/comment-on-forks.yml
We need to give explicit permissions to read other actions and then write the comment.
> explicit perms on workflow_run to read artifact, write comment

- .changes/changeTags-in-add.md
- .changes/checkout-v4-create-pr-v6.md
- .changes/config.json
- .changes/node-v20.md
- .changes/vitest-conversion.md
- .changes/workflow_run-post-comment.md
- packages/covector/src/add.ts
If the config specifies `additionalBumpTypes` and `changeTags`, we have some expectation that they want to recommend folks consider those when creating a new change file.
`covector add` now includes `additionalBumpTypes` and `changeTags` in the options to help facilitate these being included and improving the readability of changelogs.
> `covector add` now includes `additionalBumpTypes` and `changeTags`

- .changes/use-clack-over-inquirer.md
- helpers/test-scope.ts
- package-lock.json
- packages/action/tsconfig.json
- packages/covector/package.json
- packages/covector/src/add.ts
- packages/covector/src/init.ts
- packages/covector/src/run.ts
- packages/covector/test/cli/__snapshots__/command-init.test.ts.snap
- packages/covector/test/cli/command-init.test.ts
- packages/covector/test/helpers.ts
The value that inquirer provides is outshined by clack's feature set. We also didn't use much of the inquirer features that brought along an increased package size—making the swap.
It wasn't a straight swap, but we shifted the implementation to suit the altered API and improved upon some existing rough edges.
> swap clack for inquirer

- .changes/config.json
- packages/covector/src/init.ts
Using the `--provenance` in an npm publish creates an annotation on the npm registry which shows that this was published through CI.
> use --provenance for publishes to npm

- .github/workflows/run-version-or-publish.yml
- packages/covector/src/init.ts
Missed the `id-token` required to enable `provenance` for npm.
> provenance in #338 needs id-token

- .github/workflows/run-version-or-publish.yml
We scoped the permissions too tight in #340. Adjusting to allow creating GitHub Releases.
> GitHub Release needs contents: write permission

- packages/toml/package.json
We were missing metadata in the toml package to publish. Adding it.
> toml package needs more metadata for publishing

- .changes/logger-poorly-formatted-objects.md
- packages/covector/src/arbitrary.ts
- packages/covector/src/publish.ts
- packages/covector/src/status.ts
- packages/covector/src/version.ts
- packages/covector/test/integration/complex.test.ts
- packages/covector/test/integration/dry-run.test.ts
We hit an error downstream in prerelease mode where the logger was passed an object with an improper type signature. Fixing this.
This seemed to only occur in one spot in the production code, but we also missed many `--dry-run` instances as well.
> missed passing some logger functions appropriate object signature

- .changes/pass-config-to-prerelease-return.md
- packages/covector/src/status.ts
Comments on prerelease were throwing an error because the config was not passed in the return.
> pass config to prerelease return

- .github/workflows/comment-on-forks.yml
The name didn't match the workflow for commenting on forks. This meant the workflow was not run.
> comment-on-fork name fix

- .changes/change-pr-350.md
- packages/action/src/comment/formatGithubComment.ts
it links to the wrong (maybe old?) directory currently
> fix covector docs link

- .changes/action-supports-dry-run.md
- .changes/config.json
- .github/workflows/run-version-or-publish.yml
- packages/action/action.yml
- packages/action/src/index.ts
Supporting the `--dry-run` arg that users may test a publish sequence prior to officially merging.
The CLI and function already supported this, passing it through the action as an input option.
> action supports --dry-run

- .changes/action-supports-dry-run.md
- .changes/change-file-add-url-on-forks.md
- .changes/change-pr-350.md
- packages/action/src/comment/formatGithubComment.ts
The URL to create a change file on forks was broken. It was incorrectly pointing at the root repo.
> fix 'change file add' URL on forks

- .changes/status-output-options.md
- packages/action/README.md
- packages/action/src/index.ts
- packages/types/src/index.ts
Adding a few more outputs from the `status` command for use cases which want to work off the derived state.
Using the existing returns to pipe some more information into outputs. The types aren't terribly helpful at the moment, so including some guards as well.
> Additional Status Outputs
